### ISSUE TITLE
Error when trying to convert matlab based TMS-Map-data in cachefile

### ISSUE THREAD

**Issue by BettinaTrunk** [translationalneurosurgery/tool-offspect#11]
Recognizes matprot protocol as source and opens Matlab Command Window.
Error:

![create_cachefile_matlab](https://user-images.githubusercontent.com/54707165/77307815-3bda2f80-6cfa-11ea-847a-3a42f425c51d.PNG)

**Comment by agricolab** [comment]
I understand that you do have matlab installed, right? I guess this has to do with the way i call matlab as a subprocess (https://github.com/translationalneurosurgery/tool-load-tms/blob/master/matprot/convert/traces.py#L77). Tests works on  Linux but i haven't tested them on Windows. Likely some issue with `"` versus `'`.
I use https://github.com/translationalneurosurgery/tool-load-tms to load and convert the matfiles. 
Can you install and run pytest on it?
```
clone https://github.com/translationalneurosurgery/tool-load-tms 
cd tool-load-tms
pip install -r requirements.txt
pytest
```

**Comment by agricolab** [comment]
Okay, sorry, my mistake. You need to run `pip install -r tests/requirements.txt` first.

**Comment by BettinaTrunk** [comment]
Okay, I did. These are the messages:
![pytest1](https://user-images.githubusercontent.com/54707165/77325505-c16cd800-6d18-11ea-9dd7-46ddca07c3b8.PNG)

![pytest2](https://user-images.githubusercontent.com/54707165/77325522-c6ca2280-6d18-11ea-8778-1bc4c6a2b557.PNG)

**Comment by agricolab** [comment]
Okay, i pushed some changes in the hope it works. I don't have matlab installed nor windows, so i currently have no way to properly test this. Go to the tool-load-tms folder and try: 
```
git pull
pip install -e .
pytest
```
if this doesn't work, i'll have to get access to a windows machine with matlab installed, this will take a couple of days.

**Comment by BettinaTrunk** [comment]
Thank you! Unfortunately, I still get some errors:

![pytest5](https://user-images.githubusercontent.com/54707165/77397625-418d4f00-6da6-11ea-9c01-30c9cfb4c2e5.PNG)
![pytest6](https://user-images.githubusercontent.com/54707165/77397633-44883f80-6da6-11ea-85a8-3a5a1b7c2b5a.PNG)

Besides that, a matlab command window opens with some information/error (before these last changes it was basically empty) 
![pytest4](https://user-images.githubusercontent.com/54707165/77397760-7ac5bf00-6da6-11ea-9bfd-908681ec8bd0.PNG)

and the editor:
![pytest3](https://user-images.githubusercontent.com/54707165/77397787-8618ea80-6da6-11ea-960d-f158383e64e8.PNG)

**Comment by agricolab** [comment]
Thanks for running the test and the detailed description. In the failing test, we do assert that the `.m`-file exists before calling matlab. Additionally, all other tests succeed.

This means apparently, that Matlab can't find the `.m`-file although it exists. As Matlab fails, but the process was started, we try to load the converted file nonetheless. This causes the error. 

It could be related to the user-folder being abbreviated (i.e BETTIN~1). I'll try to find a workaround.

**Comment by ethanrich** [comment]
I was able to reproduce the error. Starting on it now.

**Comment by agricolab** [comment]
Great. Let's move the discussion to the correct repo (i.e.  https://github.com/translationalneurosurgery/tool-load-tms/issues/1)

**Comment by agricolab** [comment]
Fixed with https://github.com/translationalneurosurgery/tool-load-tms/commit/0bf24c87aaca2f6f4d42d305f3a5d0d361c521de
